FROM alpine 
MAINTAINER Ernest E. Teem III <sovereign313@gmail.com>
ADD defiantmail /defiantmail
ADD mail.html /mail.html
ADD setup.html /setup.html
ADD splash.html /splash.html
ADD login.html /login.html

CMD ["/defiantmail"]
